version: '3.4'

services:
  edwardhsu.lab.distributedlockwithlogging:
    image: ${DOCKER_REGISTRY-}edwardhsulabdistributedlockwithlogging
    build:
      context: .
      dockerfile: EdwardHsu.Lab.DistributedLockWithLogging/Dockerfile
  redis:
    image: redis
    ports:
      - 6379:6379
